name: OSCAL CI/CD
on:
  push:
    branches:
    - main
    - develop
    - "release-*"
  pull_request:
    branches:
    - main
    - develop
    - "release-*"
  workflow_dispatch:
jobs:
  validate-repo-markdown:
    uses: ./.github/workflows/workflow-validate-repo-markdown.yml
  validate-metaschema-artifacts:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/workflow-generate-metaschema-resources.yml
    with:
      saxon_version: 10.6
      commit_resources: false
  push-metaschema-artifacts:
    if: github.event_name == 'push'
    uses: ./.github/workflows/workflow-generate-metaschema-resources.yml
    with:
      saxon_version: 10.6
      commit_resources: true
    secrets:
      access_token: ${{ secrets.COMMIT_TOKEN }}
  validate-website-reference:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/workflow-generate-website-reference.yml
    with:
      saxon_version: 10.6
      hugo_version: 0.83.1
      calabash_version: 1.2.5-100
      commit_resources: false
  push-website-reference:
    if: github.event_name == 'push'
    uses: ./.github/workflows/workflow-generate-website-reference.yml
    with:
      saxon_version: 10.6
      hugo_version: 0.83.1
      calabash_version: 1.2.5-100
      commit_resources: true
    secrets:
      access_token: ${{ secrets.COMMIT_TOKEN }}
  validate-website:
    if: github.event_name == 'pull_request'
    needs: validate-website-reference
    uses: ./.github/workflows/workflow-generate-website.yml
    with:
      saxon_version: 10.6
      hugo_version: 0.83.1
      calabash_version: 1.2.5-100
      commit_resources: false
  push-website:
    if: github.event_name == 'push'
    needs: push-website-reference
    uses: ./.github/workflows/workflow-generate-website.yml
    with:
      saxon_version: 10.6
      hugo_version: 0.83.1
      calabash_version: 1.2.5-100
      commit_resources: true
    secrets:
      access_token: ${{ secrets.COMMIT_TOKEN }}
